spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key:  LTAI4GHcDsePkvRM9Mg26CPH
      secret-key: KqxkfrmTxohCabbIDJBE9YxMa3XtSG
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-baiyu
  application:
    name: gulimall-third-party
server:
  port: 30000


